### ISSUE TITLE
Why is minsdk 29? Couldn't it be lower?

### ISSUE THREAD

**Issue by shtolik** [RealAshampoo/kim#4]
Hi
Thanks for nice library, I was thinking about using it, but then minsdk version is set to 29. 
And I'm not sure which part forces it to be so high? I've checked it out and compile with minsdk 23 and it compiles and jvm tests pass. Could you please reduce version requirement? since otherwise projects including it won't compile with error: 

```
Execution failed for task ':androidApp:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 29 declared in library [com.ashampoo:kim-android:0.1.1]
```

**Comment by StefanOltmann** [comment]
Hi,

thank you for testing that. Yes, We can lower the min SDK.

Ashampoo Photos needs API 29 and so I didn’t test something lower.

**Comment by StefanOltmann** [comment]
@shtolik I just pushed v0.1.3 to Maven Central and it should become available in the next couple of hours. Please let me know how it works for you.

**Comment by StefanOltmann** [comment]
@shtolik It is live now on Maven Central.

**Comment by shtolik** [comment]
23 is good enough for me, thanks!
